backend:
  name: github
  repo: CHANGE_ME_OWNER/CHANGE_ME_REPO
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts_uk"
    label: "Пости (UK)"
    folder: "content/posts/uk"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Заголовок }
      - { name: date, label: Дата, widget: datetime }
      - { name: slug, label: Слаг }
      - { name: summary, label: Короткий опис, required: false }
      - { name: cover, label: Обкладинка, widget: image, required: false }
      - { name: body, label: Текст, widget: markdown }
